### ISSUE TITLE
the issue when run the pkgstack in docker

### ISSUE THREAD

**Issue by ownport** [ownport/pkgstack#1]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/pkgstack/__main__.py", line 1, in <module>
    from main import run
  File "/usr/lib/python2.7/site-packages/pkgstack/main.py", line 14, in <module>
    from vendor.lib2x import yaml
ImportError: No module named vendor.lib2x
```

**Comment by ownport** [comment]
no one vendor modules  were imported during sdist operation
